server:
  port: 9000

spring:
  application:
    name: "cards"
  profiles:
    active:
      - "prod"
  datasource:
    username: root
    password: 'root'
    url: jdbc:mysql://localhost:3308/cardsdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: "optional:configserver:http://localhost:8071"

management:
  endpoints:
    web:
      exposure:
        include: "*"