build:
  version: "3.0"

accounts:
  message: "Welcome to MicroService Bank App ...local Api"
  contactDetails:
    name: Henry Taiwo - HT
    email: taiowh782@gmail.com
  onCallSupport:
    - +(234)8 159 602 684
