build:
  version: "1.0"

loans:
  message: "Welcome to MicroService Bank App ...Loans prod Apis"
  contactDetails:
    name: Henry Taiwo - Developer
    email: devwhenry@gmail.com
  onCallSupport:
    - +(234)8 159 602 685
