build:
  version: "3.0"

loans:
  message: "Welcome to MicroService Bank App ...local Loans Api"
  contactDetails:
    name: Henry Taiwo - HT
    email: taiowh782@gmail.com
  onCallSupport:
    - +(234)8 159 602 684
